// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    parent_session_id,
    title,
    message_count,
    prompt_tokens,
    completion_tokens,
    cost,
    summary_message_id,
    current_tokens,
    updated_at,
    created_at,
    is_stateless,
    service,
    is_pinned
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    null,
    0,
    strftime('%s', 'now'),
    strftime('%s', 'now'),
    0,
    '',
    0
) RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, current_tokens, is_stateless, service, is_pinned
`

type CreateSessionParams struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.ParentSessionID,
		arg.Title,
		arg.MessageCount,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CurrentTokens,
		&i.IsStateless,
		&i.Service,
		&i.IsPinned,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteSessionStmt, deleteSession, id)
	return err
}

const getLastSession = `-- name: GetLastSession :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, current_tokens, is_stateless, service, is_pinned
FROM sessions
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetLastSession(ctx context.Context) (Session, error) {
	row := q.queryRow(ctx, q.getLastSessionStmt, getLastSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CurrentTokens,
		&i.IsStateless,
		&i.Service,
		&i.IsPinned,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, current_tokens, is_stateless, service, is_pinned
FROM sessions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.queryRow(ctx, q.getSessionByIDStmt, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CurrentTokens,
		&i.IsStateless,
		&i.Service,
		&i.IsPinned,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, current_tokens, is_stateless, service, is_pinned
FROM sessions
WHERE parent_session_id is NULL
ORDER BY is_pinned DESC, updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.Todos,
				&i.CurrentTokens,
				&i.IsStateless,
				&i.Service,
				&i.IsPinned,
			); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSession = `-- name: RenameSession :exec
UPDATE sessions
SET
    title = ?
WHERE id = ?
`

type RenameSessionParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) RenameSession(ctx context.Context, arg RenameSessionParams) error {
	_, err := q.exec(ctx, q.renameSessionStmt, renameSession, arg.Title, arg.ID)
	return err
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET
    title = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    summary_message_id = ?,
    cost = ?,
    todos = ?,
    current_tokens = ?
WHERE id = ?
RETURNING id, parent_session_id, title, message_count, prompt_tokens, completion_tokens, cost, updated_at, created_at, summary_message_id, todos, current_tokens, is_stateless, service, is_pinned
`

type UpdateSessionParams struct {
	Title            string         `json:"title"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Cost             float64        `json:"cost"`
	Todos            sql.NullString `json:"todos"`
	CurrentTokens    int64          `json:"current_tokens"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.queryRow(ctx, q.updateSessionStmt, updateSession,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.SummaryMessageID,
		arg.Cost,
		arg.Todos,
		arg.CurrentTokens,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ParentSessionID,
		&i.Title,
		&i.MessageCount,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.Cost,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.SummaryMessageID,
		&i.Todos,
		&i.CurrentTokens,
		&i.IsStateless,
		&i.Service,
		&i.IsPinned,
	)
	return i, err
}

const updateSessionTitleAndUsage = `-- name: UpdateSessionTitleAndUsage :exec
UPDATE sessions
SET
    title = ?,
    prompt_tokens = prompt_tokens + ?,
    completion_tokens = completion_tokens + ?,
    cost = cost + ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSessionTitleAndUsageParams struct {
	Title            string  `json:"title"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	Cost             float64 `json:"cost"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateSessionTitleAndUsage(ctx context.Context, arg UpdateSessionTitleAndUsageParams) error {
	_, err := q.exec(ctx, q.updateSessionTitleAndUsageStmt, updateSessionTitleAndUsage,
		arg.Title,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.Cost,
		arg.ID,
	)
	return err
}

const updateStatelessSession = `-- name: UpdateStatelessSession :exec
UPDATE sessions
SET
    is_stateless = ?,
    service = ?
WHERE id = ?
`

type UpdateStatelessSessionParams struct {
	IsStateless int64  `json:"is_stateless"`
	Service     string `json:"service"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateStatelessSession(ctx context.Context, arg UpdateStatelessSessionParams) error {
	_, err := q.exec(ctx, q.updateStatelessSessionStmt, updateStatelessSession,
		arg.IsStateless,
		arg.Service,
		arg.ID,
	)
	return err
}
const listStatelessSessions = `-- name: ListStatelessSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens,
       cost, updated_at, created_at, summary_message_id, todos, current_tokens,
       is_stateless, service, is_pinned
FROM sessions
WHERE is_stateless = 1 AND (?1 = '' OR service = ?1)
ORDER BY created_at DESC
`

type ListStatelessSessionsParams struct {
	ServiceFilter string `json:"service_filter"`
}

func (q *Queries) ListStatelessSessions(ctx context.Context, arg ListStatelessSessionsParams) ([]Session, error) {
	rows, err := q.query(ctx, q.listStatelessSessionsStmt, listStatelessSessions, arg.ServiceFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.Todos,
				&i.CurrentTokens,
				&i.IsStateless,
				&i.Service,
				&i.IsPinned,
			); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
const updatePinned = `-- name: UpdatePinned :exec
UPDATE sessions
SET
    is_pinned = ?
WHERE id = ?
`

type UpdatePinnedParams struct {
	IsPinned int64  `json:"is_pinned"`
	ID        string `json:"id"`
}

func (q *Queries) UpdatePinned(ctx context.Context, arg UpdatePinnedParams) error {
	_, err := q.exec(ctx, q.updatePinnedStmt, updatePinned, arg.IsPinned, arg.ID)
	return err
}

const listPrunableSessions = `-- name: ListPrunableSessions :many
SELECT id, parent_session_id, title, message_count, prompt_tokens, completion_tokens,
       cost, updated_at, created_at, summary_message_id, todos, current_tokens,
       is_stateless, service, is_pinned
FROM sessions
WHERE parent_session_id IS NULL
  AND is_pinned = 0
  AND updated_at <= ?1
ORDER BY updated_at ASC
`

func (q *Queries) ListPrunableSessions(ctx context.Context, updatedAt int64) ([]Session, error) {
	rows, err := q.query(ctx, q.listPrunableSessionsStmt, listPrunableSessions, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ParentSessionID,
			&i.Title,
			&i.MessageCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.Cost,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.SummaryMessageID,
			&i.Todos,
			&i.CurrentTokens,
			&i.IsStateless,
			&i.Service,
			&i.IsPinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkDeleteSessions = `-- name: BulkDeleteSessions :exec
DELETE FROM sessions
WHERE parent_session_id IS NULL
  AND is_pinned = 0
  AND updated_at <= ?
`

func (q *Queries) BulkDeleteSessions(ctx context.Context, updatedAt int64) error {
	_, err := q.exec(ctx, q.bulkDeleteSessionsStmt, bulkDeleteSessions, updatedAt)
	return err
}